baseURL = "https://lamonega.com.ar"
theme = "hugo-bearcub"
copyright = "Laureano Lamonega (CC BY 4.0)"
defaultContentLanguage = "es"
enableRobotsTXT = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[languages]
  [languages.es]
    title = "Laureano Lamonega"
    label = "es-AR 🇦🇷"
    locale = "es-AR"
    contentDir = "content"
    [languages.es.params]
      madeWith = "Hecho con [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  description = "Laureano Lamonega"
  favicon = "images/favicon.svg"
  images = ["images/share.webp"]
  timeFormat = "2 de January de 2006"
  generateSocialCard = true
  [params.author]
    name = "Laureano Lamonega"